name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.27.1"]
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@v7
      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
